added colorthemes for project in main.jsx, with linter this time
tablebook/tablebook pull request #43
Opened 2024-03-07 23:19 UTC by vsuusi

- added initial colours based on logo/icon, can be adjusted later
- wrapped the app with theme provider so it is accessible from anywhere

2024-03-07 23:22 UTC, vsuusi commented
tuli ylimääränen pr ku laukes eka ilman lintteriä, voidaa vaikka maanantaina kattoo jos tarvii siivoilla yms, mutta se on siis suljettu nyt ja tämä on kunnossa, hyvä ku paiplain heti nappas kii tosta lintin puuttumisesta (Y)

2024-03-08 12:29 UTC, ArtoLaitinen requested changes
Add the text colors for at least primary, secondary and background.
For example for primary do it like this:
primary: {
   main: "#7E83A0",
   contrastText: "COLOR HERE",
},

2024-03-08 12:37 UTC, vsuusi commented
> Add the text colors for at least primary, secondary and background. For example for primary do it like this: primary: { main: "#7E83A0", contrastText: "COLOR HERE", },

Material UI defines text color automatically based on primary color if not defined, thus there is no need for contrastText

2024-03-08 12:39 UTC, ArtoLaitinen approved these changes

2024-03-08 12:40 UTC, merged